export const mytablecontent6 = [
  {
    column1: "黃○鋒",
    column2: "大家長",
    column3: "臺北市政府",
    column4: "草包鋒兄",
    title: "臺北市政府",
    alt: "臺北市政府",
    link: "https://www-ws.gov.taipei/001/Upload/297/relfile/7725/97235/5624f50e-9193-4c61-88f3-6a8686ee8adb.pdf",
    map: "https://www.google.com/maps/search/臺北市政府",
  },
  {
    column1: "塗○傑",
    column2: "董事",
    column3: "臺北農產運銷公司",
    column4: "國中同班同學",
    title: "臺北農產運銷公司",
    alt: "臺北農產運銷公司",
    link: "https://www.tapmc.com.tw/",
    map: "https://www.google.com/maps/search/臺北農產運銷公司",
  },
  {
    column1: "劉○萱",
    column2: "局長",
    column3: "臺北市政府環境保護局",
    column4: "高一同班同學",
    title: "臺北市政府環境保護局",
    alt: "臺北市政府環境保護局",
    link: "https://www.dep.gov.taipei/",
    map: "https://www.google.com/maps/search/臺北市政府環境保護局",
  },
  {
    column1: "賴○蓉",
    column2: "局長",
    column3: "臺北市政府財政局",
    column4: "高中同班同學",
    title: "臺北市政府財政局",
    alt: "臺北市政府財政局",
    link: "https://dof.gov.taipei/",
    map: "https://www.google.com/maps/search/臺北市政府財政局",
  },
];
