export const mytablecontent3 = [
  {
    column1: "天晟/譚詠康(身心科)",
    column2: "05/26(一)~06/05(四)",
    column3: "06/23(一)~07/03(四",
    column4: "07/31(四)下午",
    title: "中壢天晟醫院",
    alt: "中壢天晟醫院",
    link: "https://www.tcmg.com.tw/index.php/main/schedule_time?id=14",
  },
  {
    column1: "天晟/黃信凱(心臟內科)",
    column2: "[預定改成07/11(五)下午]",
    column3: "05/27(二)~06/06(五)",
    column4: "07/04(五)下午",
    title: "中壢天晟醫院",
    alt: "中壢天晟醫院",
    link: "https://www.tcmg.com.tw/index.php/main/schedule_time?id=18",
  },
  {
    column1: "范光迪/陳建鴻",
    column2: "[預定改成06/00(無)上午]",
    column3: "[預定改成07/00(無)上午]",
    column4: "06/27(五)上午",
    title: "范光迪診所",
    alt: "范光迪診所",
    link: "https://www.fanktclinic.com",
  },
  {
    column1: "晶鑽牙醫",
    column2: "預定08/00(無)下午]",
    column3: "",
    column4: "",
    title: "晶鑽牙醫",
    alt: "晶鑽牙醫",
    link: "https://www.1111.com.tw/corp/54938920",
  },
  {
    column1: "聯新/胸腔外科",
    column2: "預定09/00(五)下午]",
    column3: "",
    column4: "",
    title: "聯新國際醫院",
    alt: "聯新國際醫院",
    link: "https://www.landseedhospital.com.tw/tw/outpatient/time",
  },
];
